name: Deploy Trades Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev or sit)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4

      - name: Authenticate to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "${{ secrets.ENV_DEV }}" > .env
          else
            echo "${{ secrets.ENV_SIT }}" > .env
          fi

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no $(grep SERVER_USER .env | cut -d'=' -f2)@$(grep SERVER_IP .env | cut -d'=' -f2) "
            cd /opt/trades_deployment &&
            git pull &&
            docker compose --env-file .env pull &&
            docker compose --env-file .env up -d
          "
